<?php

namespace Classes;

use Random\Randomizer;
require_once "Classes/BasePage.php";


class Dice extends BasePage
{
    private const _diceSidesStyles = array(
        1 => "DiceMain Dice1",
        2 => "DiceMain Dice2",
        3 => "DiceMain Dice3",
        4 => "DiceMain Dice4",
        5 => "DiceMain Dice5",
        6 => "DiceMain Dice6"
    );

    private int $_diceValue;

    public function getDiceValue(): int
    {
        return $this->_diceValue;
    }

    public function ThrowDice(): void
    {
        $rand = new Randomizer();
        $this->_diceValue = rand(1, 6);
    }

    public function EchoDieImage() : void
    {
        $diceStyle = self::_diceSidesStyles[$this->getDiceValue()];
        echo <<<DICE_IMAGE
            <div class="$diceStyle"></div>
        DICE_IMAGE;
    }

    public function EchoHeader(): void
    {
        parent::EchoHeader(); // TODO: Change the autogenerated stub
        echo <<<INCLUDE_CSS
        <link rel="stylesheet" href="/css/DiceSides.css">
        INCLUDE_CSS;
    }
}